// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.2
// source: err.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_OK  ErrCode = 0
	ErrCode_ERR ErrCode = -1
	// 1000 - 1999 通用错误
	ErrCode_UpParam ErrCode = 1000 // 上行参数错误
	// 2000 - 2999 用户错误
	ErrCode_AccountRegister_NameInvalid ErrCode = 2000 // 用户名不合法
	ErrCode_AccountRegister_PwdInvalid  ErrCode = 2001 // 密码不合法
	ErrCode_AccountRegister_NameExist   ErrCode = 2002 // 用户名已存在
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "OK",
		-1:   "ERR",
		1000: "UpParam",
		2000: "AccountRegister_NameInvalid",
		2001: "AccountRegister_PwdInvalid",
		2002: "AccountRegister_NameExist",
	}
	ErrCode_value = map[string]int32{
		"OK":                          0,
		"ERR":                         -1,
		"UpParam":                     1000,
		"AccountRegister_NameInvalid": 2000,
		"AccountRegister_PwdInvalid":  2001,
		"AccountRegister_NameExist":   2002,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_err_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_err_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_err_proto_rawDescGZIP(), []int{0}
}

var File_err_proto protoreflect.FileDescriptor

var file_err_proto_rawDesc = []byte{
	0x0a, 0x09, 0x65, 0x72, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2a, 0x94, 0x01, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06,
	0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x52, 0x52, 0x10, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x12, 0x0c, 0x0a, 0x07, 0x55, 0x70, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x10, 0xe8, 0x07, 0x12, 0x20, 0x0a, 0x1b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0xd0, 0x0f, 0x12, 0x1f, 0x0a, 0x1a, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x50, 0x77, 0x64, 0x49,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0xd1, 0x0f, 0x12, 0x1e, 0x0a, 0x19, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x4e, 0x61, 0x6d,
	0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0xd2, 0x0f, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_err_proto_rawDescOnce sync.Once
	file_err_proto_rawDescData = file_err_proto_rawDesc
)

func file_err_proto_rawDescGZIP() []byte {
	file_err_proto_rawDescOnce.Do(func() {
		file_err_proto_rawDescData = protoimpl.X.CompressGZIP(file_err_proto_rawDescData)
	})
	return file_err_proto_rawDescData
}

var file_err_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_err_proto_goTypes = []interface{}{
	(ErrCode)(0), // 0: proto.ErrCode
}
var file_err_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_err_proto_init() }
func file_err_proto_init() {
	if File_err_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_err_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_err_proto_goTypes,
		DependencyIndexes: file_err_proto_depIdxs,
		EnumInfos:         file_err_proto_enumTypes,
	}.Build()
	File_err_proto = out.File
	file_err_proto_rawDesc = nil
	file_err_proto_goTypes = nil
	file_err_proto_depIdxs = nil
}
